name: pica_crawler GPT

on:
  #将下面两行代码取消注释
  #schedule:
  #- cron: "0 0 * * *"
  workflow_dispatch:
  push:
    paths:
      - 'mainchat.py'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: install dependency
        run: |
          pip install --upgrade pip
          pip install urllib3
          pip install requests
      - name: main logic
        env:
          PICA_SECRET_KEY: ${{secrets.PICA_SECRET_KEY}}
          PICA_ACCOUNT: ${{secrets.PICA_ACCOUNT}}
          PICA_PASSWORD: ${{secrets.PICA_PASSWORD}}
          # 过滤分区 用,分隔 
          CATEGORIES: 性轉換
          # CATEGORIES_RULE 过滤规则    INCLUDE: 包含任意一个分区就下载  EXCLUDE: 包含任意一个分区就不下载
          CATEGORIES_RULE: INCLUDE
          # 订阅的关键词,会下载x天范围内上传的漫画    为空则关闭关键词订阅 用,分隔
          SUBSCRIBE_KEYWORD: Okayushop (Okayu),眼ん月堂 (至室),RIX (マミヤ),ふずめ,Asunaro Neat. (ろんな),いづみ(CHIPS),若宮参太,BEHIND THE MASK (蜜子。),牧野坂シンイチ,狼亮輔,桃河馬,egoistic media(棗ふみこ),愛兒(HENJIN69),炭酸プロテイン柏木,Imitation Moon (成海優),奥森ボウイ,海鮮堂(マクジラ),シザリオン (しーざー),伊佐美ノゾミ,折川,Siesta (九廊),不二河聡,Duckgu,安治ぽん太郎,みこやん,なかよし産婦人科 (まてつ),吉田悟郎商會 (吉田悟郎),憑依k,醉卧星河,あむぁいおかし製作所 (つく丸、なまむぎ),すらいむのかんむり (かんむり),アンソロジー,DA HOOTCH (新堂エル),恥辱庵,ゆきしずく (ながねこ),Duokuma,高崎たけまる,わろみん家 (わろみん),神谷ズズ,DAGASI,SeaFox (霧咲白狐),くれじっと,CHARAN PORAN (猫乃またたび),ZPT (ポミヲ),もけぷーず,ColdBloodedTwilight,カネコナオヤ,ツリサス,jm600r,クリスタルな洋介,くろむら基人,浅野屋 (キッツ),絵を描くマン (Eman),TSF no F (べってぃ),pulltop,あむぁいおかし製作所 (ゆーきぃ),すえみつぢっか,ろくでなしの詩(俊),即オチ少女 (鏡乃もちこ),羽贺ソウケン 長尾件,Blue Crest (蒼野アキラ),花巻かえる,憑依の刻,银发贫乳控,矢吹健太朗,柊ぽぷら,原作：富士防人  作画：外冈马骨,くまQM,あむぁいおかし製作所 (かいわれ大根、あほげきのこ),晴濑ひろき,おひつじ,そらりれゆ,KABA,Tempest (伊巻てん、温野りょく),THE猥談 (鬱ノ宮うかつ),永田まりあ,うどんや (鬼月あるちゅ、ZAN),Tera Stellar (小山内にい),MAX&Cool,L.P.E.G. (まる寝子),自宅 (へも),モモモーモー伯爵,U.R.C(桃屋しょう貓),たまの父,伊藤屋,谷口さん,條仔、あるべんと,あむぁいおかし製作所 (かいわれ大根、つく丸),うえにあるみかん,小飛鼠,UTEN+ (雨天あめか),山本同人,あむぁいおかし製作所 (倉塚りこ),STUDIO&PIM-DOG,不明,エレクトさわる,ノードラッグハイテンション(水乃カルキ),ヤバ谷らんど (ほみなみあ),ハシモトミツ,ウェルト,聖華快楽書店 (エルトリア、夜空さくら、nikujaga),ねことうふ,かるま龍狼,狐梅珈琲店 (鹽、彩月あたん),KH. (有紀),夢先案内回覧版 (ひろひろき),Marialite (ゆーきぃ),Arisane (Arisa Yoshi),性轉換,ジンギスカンの玉葱は俺の嫁 (谷口さん),龍企画 (龍炎狼牙),ciaociao (あらきかなお),おたまジャグジー (たまの父),矢吹健太郎,マメック星,きのこのみ (konomi),しまなみ (あーきぺらご),橘由宇,桃純 (ももずみ純),拍手喝罪（我宮てれさ）,中川優,竹とんぼ (菜葉),つゆだくシュガー (すずしも),黑澤清崇,史鬼匠人,もげたま (田中森よこた),千之 ナイフ(Senno Knife)(千之刃),共謀猫 (春ヲ、 不二岳、 8205),ノボッチ製作所 (南雲龍一),影魔尤影,タカスギコウ,アラタ
          # 订阅的x天范围     git actions运行时填小一点,免得漫画过多邮箱推送不了,本地运行时随便填
          SUBSCRIBE_DAYS: 900000000
          # 允许在下载完成后发送自定义消息,为空则不发送 例: https://api.day.app/{your_keys}/picacg下载成功
          BARK_URL: ${{secrets.BARK_URL}}
          #每下载一本漫画的间隔时间(秒),在下载大量漫画时可以设置的稍微大一些,免得哔咔服务器响应不过来
          INTERVAL_TIME: 5
        run: |
          python mainchat.py
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add downl.txt
          git add run_time_history.txt
          7z a -r "comics/finder-result.zip" "comics/*"
          git commit -m "更新"
      - name: Push
        uses:  ad-m/github-push-action@master
        with:
              branch: master
      - name: Get Time
        run: |
            echo "TAG_TIME=$(date +"%Y-%m-%d-%H-%M")" >> $GITHUB_ENV
            echo "DISPLAY_TIME=$(date +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
  
      - name: 自动释放
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.TAG_TIME }}"
          prerelease: true
          title: "finder-result ${{ env.DISPLAY_TIME }}"
          files: |
            comics/finder-result.zip
