name: pica1-40

on:
  #将下面两行代码取消注释
  #schedule:
    #- cron: "0 0 * * *"
  workflow_dispatch:
  push:
    paths:
      - 'main.py'
      - '.github/workflows/pica1-40.yml'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: install dependency
        run: |
          pip install --upgrade pip
          pip install urllib3
          pip install requests
      - name: main logic
        env:
          PICA_SECRET_KEY: ${{secrets.PICA_SECRET_KEY}}
          PICA_ACCOUNT: ${{secrets.PICA_ACCOUNT}}
          PICA_PASSWORD: ${{secrets.PICA_PASSWORD}}
          # 过滤分区 用,分隔 
          CATEGORIES: 性轉換
          # CATEGORIES_RULE 过滤规则    INCLUDE: 包含任意一个分区就下载  EXCLUDE: 包含任意一个分区就不下载
          CATEGORIES_RULE: INCLUDE
          # 订阅的关键词,会下载x天范围内上传的漫画    为空则关闭关键词订阅 用,分隔
          SUBSCRIBE_KEYWORD: あむぁいおかし製作所 (かいわれ大根、つく丸),RIX (マミヤ),ジンギスカンの玉葱は俺の嫁 (谷口さん),STUDIO&PIM-DOG,羽贺ソウケン 長尾件,Siesta (九廊),矢吹健太郎,くれじっと,なかよし産婦人科 (まてつ),晴濑ひろき,牧野坂シンイチ,KABA,おたまジャグジー (たまの父),いづみ(CHIPS),しまなみ (あーきぺらご),シザリオン (しーざー),Okayushop (Okayu),Arisane (Arisa Yoshi),DA HOOTCH (新堂エル),TSF no F (べってぃ),おひつじ,THE猥談 (鬱ノ宮うかつ),若宮参太,ろくでなしの詩(俊),jm600r,くろむら基人,影魔尤影,ゆきしずく (ながねこ),神谷ズズ,みこやん,憑依の刻,浅野屋 (キッツ),共謀猫 (春ヲ、 不二岳、 8205),狐梅珈琲店 (鹽、彩月あたん),Tera Stellar (小山内にい),アラタ,Duokuma,银发贫乳控,夢先案内回覧版 (ひろひろき),BEHIND THE MASK (蜜子。),Duckgu
          # 订阅的x天范围     git actions运行时填小一点,免得漫画过多邮箱推送不了,本地运行时随便填
          SUBSCRIBE_DAYS: 900000000
          # 允许在下载完成后发送自定义消息,为空则不发送 例: https://api.day.app/{your_keys}/picacg下载成功
          BARK_URL: ${{secrets.BARK_URL}}
          #每下载一本漫画的间隔时间(秒),在下载大量漫画时可以设置的稍微大一些,免得哔咔服务器响应不过来
          INTERVAL_TIME: 5
        run: |
          python main.py
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add downl.txt
          git add run_time_history.txt
          7z a -r "comics/finder-result.zip" "comics/*"
          git commit -m "更新"
      - name: Push
        uses:  ad-m/github-push-action@master
        with:
              branch: master
      - name: 获取当前时间
        run: |
            echo "TAG_TIME=$(date +"%Y-%m-%d-%H-%M")" >> $GITHUB_ENV
            echo "DISPLAY_TIME=$(date +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
  
      - name: 自动释放
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.TAG_TIME }}"
          prerelease: true
          title: "finder-result ${{ env.DISPLAY_TIME }}"
          files: |
            comics/finder-result.zip
