name: pica_crawler

on:
  #将下面两行代码取消注释
  #schedule:
    #- cron: "0 0 * * *"
  workflow_dispatch:
  push:
    paths:
      - 'config/config.ini'
      - '.github/workflows/pica_crawler_actions.yml'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.10"
      - name: install dependency
        run: |
          pip install --upgrade pip
          pip install urllib3
          pip install requests
      - name: main logic
        env:
          PICA_SECRET_KEY: ${{secrets.PICA_SECRET_KEY}}
          PICA_ACCOUNT: ${{secrets.PICA_ACCOUNT}}
          PICA_PASSWORD: ${{secrets.PICA_PASSWORD}}
          # 允许在下载完成后发送自定义消息,为空则不发送 例: https://api.day.app/{your_keys}/picacg下载成功
          BARK_URL: ${{secrets.BARK_URL}}
        run: |
          python ./src/main.py
          git add ./data/downloaded.db
          git add ./logs
          7z a -r "comics/finder-result.zip" "comics/*"
      # comics文件夹下的所有漫画都会被打成一个压缩包,并上传到actions artifact. 如果不配置邮箱推送功能,可以用这个来下载到漫画
      - name: upload-artifact
        uses: actions/upload-artifact@v4
        with:
              branch: master
      - name: Get Time
        run: |
            echo "TAG_TIME=$(date +"%Y-%m-%d-%H-%M")" >> $GITHUB_ENV
            echo "DISPLAY_TIME=$(date +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
      - name: 自动释放
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.TAG_TIME }}"
          prerelease: true
          title: "finder-result ${{ env.DISPLAY_TIME }}"
          files: |
            comics/finder-result.zip
      - name: "上传"
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add ./data/downloaded.db
          git commit -m "更新"
