name: pica1-40

on:
  schedule:
    - cron: "0 0 * * *"  # 每天UTC 00:00运行
  workflow_dispatch:  # 允许手动触发
  push:
    paths:
      - 'main.py'
      - '.github/workflows/pica1-40.yml'

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 设置任务超时时间为6小时
    steps:
      - uses: actions/checkout@v4  # 使用最新的稳定版本
        with:
          fetch-depth: 1  # 优化克隆深度

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip  # 启用pip缓存

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install urllib3 requests
        continue-on-error: true  # 允许安装失败时继续执行
        retries: 3  # 失败时重试3次
      - name: Run crawler
        env:
          PICA_SECRET_KEY: ${{secrets.PICA_SECRET_KEY}}
          PICA_ACCOUNT: ${{secrets.PICA_ACCOUNT}}
          PICA_PASSWORD: ${{secrets.PICA_PASSWORD}}
          # 过滤分区 用,分隔 
          CATEGORIES: 性轉換
          # CATEGORIES_RULE 过滤规则    INCLUDE: 包含任意一个分区就下载  EXCLUDE: 包含任意一个分区就不下载
          CATEGORIES_RULE: INCLUDE
          # 订阅的关键词,会下载x天范围内上传的漫画    为空则关闭关键词订阅 用,分隔
          SUBSCRIBE_KEYWORD: あむぁいおかし製作所 (かいわれ大根、つく丸),RIX (マミヤ),ジンギスカンの玉葱は俺の嫁 (谷口さん),STUDIO&PIM-DOG,羽贺ソウケン 長尾件,Siesta (九廊),矢吹健太郎,くれじっと,なかよし産婦人科 (まてつ),晴濑ひろき,牧野坂シンイチ,KABA,おたまジャグジー (たまの父),いづみ(CHIPS),しまなみ (あーきぺらご),シザリオン (しーざー),Okayushop (Okayu),Arisane (Arisa Yoshi),DA HOOTCH (新堂エル),TSF no F (べってぃ),おひつじ,THE猥談 (鬱ノ宮うかつ),若宮参太,ろくでなしの詩(俊),jm600r,くろむら基人,影魔尤影,ゆきしずく (ながねこ),神谷ズズ,みこやん,憑依の刻,浅野屋 (キッツ),共謀猫 (春ヲ、 不二岳、 8205),狐梅珈琲店 (鹽、彩月あたん),Tera Stellar (小山内にい),アラタ,Duokuma,银发贫乳控,夢先案内回覧版 (ひろひろき),BEHIND THE MASK (蜜子。),Duckgu
          # 订阅的x天范围     git actions运行时填小一点,免得漫画过多邮箱推送不了,本地运行时随便填
          SUBSCRIBE_DAYS: 900000000
          # 允许在下载完成后发送自定义消息,为空则不发送 例: https://api.day.app/{your_keys}/picacg下载成功
          BARK_URL: ${{secrets.BARK_URL}}
          #每下载一本漫画的间隔时间(秒),在下载大量漫画时可以设置的稍微大一些,免得哔咔服务器响应不过来
          INTERVAL_TIME: 5
        run: |
          # 运行爬虫脚本
          python ./src/main.py || exit 1  # 如果脚本失败则退出

      - name: Prepare artifacts
        if: success()
        run: |
          # 压缩comics目录，排除不必要的文件
          7z a -r "comics/finder-result.zip" "comics/*" -x!*.tmp -x!*.log

      - name: Update repository
        if: success()
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add ./data/downloaded.db ./logs
          git commit -m "Update: $(date +"%Y-%m-%d %H:%M:%S") - 自动更新下载记录和日志"
      - name: Push changes
        uses: ad-m/github-push-action@master
        if: success()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master

      - name: Set release time
        if: success()
        run: |
          echo "TAG_TIME=$(date +"%Y-%m-%d-%H-%M")" >> $GITHUB_ENV
          echo "DISPLAY_TIME=$(date +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV

      - name: Create release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        if: success()
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "1-40-${{ env.TAG_TIME }}"
          prerelease: true
          title: "Finder Result 1-40 ${{ env.DISPLAY_TIME }}"
          files: comics/finder-result.zip
