name: pica_crawler

on:
  #将下面两行代码取消注释
  #schedule:
    #- cron: "0 0 * * *"
  workflow_dispatch:
  push:
    paths:
      - 'main.py'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: install dependency
        run: |
          pip install --upgrade pip
          pip install urllib3
          pip install requests
      - name: main logic
        env:
          PICA_SECRET_KEY: ${{secrets.PICA_SECRET_KEY}}
          PICA_ACCOUNT: ${{secrets.PICA_ACCOUNT}}
          PICA_PASSWORD: ${{secrets.PICA_PASSWORD}}
          # 过滤分区 用,分隔 
          CATEGORIES: 性轉換
          # CATEGORIES_RULE 过滤规则    INCLUDE: 包含任意一个分区就下载  EXCLUDE: 包含任意一个分区就不下载
          CATEGORIES_RULE: INCLUDE
          # 订阅的关键词,会下载x天范围内上传的漫画    为空则关闭关键词订阅 用,分隔
          SUBSCRIBE_KEYWORD: 性轉換,Okayushop (Okayu),おひつじ,自宅 (へも),なかよし産婦人科 (まてつ),KH. (有紀),中川優,かるま龍狼,桃河馬,ろくでなしの詩(俊),神谷ズズ,浅野屋 (キッツ),UTEN+ (雨天あめか),L.P.E.G. (まる寝子),恥辱庵,炭酸プロテイン柏木,眼ん月堂 (至室),银发贫乳控,矢吹健太朗,海鮮堂(マクジラ),柊ぽぷら,史鬼匠人,DAGASI,Siesta (九廊),つゆだくシュガー (すずしも),モモモーモー伯爵,Imitation Moon (成海優),條仔、あるべんと,Buta99,織島ユポポ,すえみつぢっか,おたまジャグジー (たまの父),不咕鸟汉化组,悦文社,みこやん,TSFのF (NOMU),夢先案内回覧版 (ひろひろき),ノボッチ製作所 (南雲龍一),fu-ta,くまQM,あむぁいおかし製作所 (かいわれ大根、あほげきのこ),Duckgu,山本同人,pulltop,いづみ(CHIPS),わろみん家 (わろみん),カネコナオヤ,聖華快楽書店 (エルトリア、夜空さくら、nikujaga),タカスギコウ,憑依の刻,ジンギスカンの玉葱は俺の嫁 (谷口さん),あむぁいおかし製作所 (ゆーきぃ),Arisane (Arisa Yoshi),小飛鼠,影魔尤影,マメック星,拍手喝罪（我宮てれさ）,jm600r,あむぁいおかし製作所 (つく丸、なまむぎ),ZPT (ポミヲ),あむぁいおかし製作所 (倉塚りこ),橘由宇,若宮参太,花巻かえる,不明,アンソロジー,龍企画 (龍炎狼牙),竹とんぼ (菜葉),MAX&Cool,くれじっと,狐梅珈琲店 (鹽、彩月あたん),そらりれゆ,奥森ボウイ,永田まりあ,RIX (マミヤ),うどんや (鬼月あるちゅ、ZAN),U.R.C(桃屋しょう貓),羽贺ソウケン 長尾件,くろむら基人,STUDIO&PIM-DOG,ハシモトミツ,THE猥談 (鬱ノ宮うかつ),しまなみ (あーきぺらご),ノードラッグハイテンション(水乃カルキ),ふずめ,谷口さん,桃純 (ももずみ純),ゆきしずく (ながねこ),うえにあるみかん,きのこのみ (konomi),ciaociao (あらきかなお),Duokuma,矢吹健太郎,たまの父,Asunaro Neat. (ろんな),Tempest (伊巻てん、温野りょく),BEHIND THE MASK (蜜子。),KABA,Marialite (ゆーきぃ),クリスタルな洋介,吉田悟郎商會 (吉田悟郎),ウェルト,すらいむのかんむり (かんむり),もげたま (田中森よこた),I'm moralist (柳原ミツキ、犬侍、かに村えびお),千之 ナイフ(Senno Knife)(千之刃),高崎たけまる,折川,TSF no F (べってぃ),あむぁいおかし製作所 (かいわれ大根、つく丸),晴濑ひろき,不二河聡,伊佐美ノゾミ,狼亮輔,egoistic media(棗ふみこ),安治ぽん太郎,アラタ,エレクトさわる,黑澤清崇,牧野坂シンイチ,Blue Crest (蒼野アキラ)
          # 订阅的x天范围     git actions运行时填小一点,免得漫画过多邮箱推送不了,本地运行时随便填
          SUBSCRIBE_DAYS: 900000000
        run: |
          python main.py
          git add downl.txt
          git add run_time_history.txt
          7z a -r "comics/finder-result.zip" "comics/*"
      # - name: upload-artifact
      #   uses: actions/upload-artifact@v3.1.0
      #   with:
      #     name: pica-comics
      #     path: comics/
      #     retention-days: 9
      - name: commit & push
        uses: actions-go/push@master
        with:
          author-email: 'actions@github.com'
          author-name: 'GitHub Actions'
          commit-message: 'update downloaded comics'
          token: ${{ secrets.GIT_TOKEN }}
      - name: Get Time
        run: |
            echo "TAG_TIME=$(date +"%Y-%m-%d-%H-%M")" >> $GITHUB_ENV
            echo "DISPLAY_TIME=$(date +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
  
      - name: 自动释放
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.TAG_TIME }}"
          prerelease: true
          title: "finder-result ${{ env.DISPLAY_TIME }}"
          files: |
            comics/finder-result.zip
