name: 测试

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/去重复.yml' # 工作流定义
      - '1.py' # 下载脚本

jobs:
  crawler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Dependency
        run: |
          python -m pip install --upgrade pip
      - name: 运行下载脚本
        run: |
          python 1.py
      - name: Commit change
        run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Actions"
            git pull origin master
            git add new_list.txt
            git commit -m "$(date '+%Y-%m-%d %H:%M:%S')合并节点"
      - name: Push
        uses:  ad-m/github-push-action@master
        with:
            branch: master